export const ADDPRODUCTINFORS = "ADDPRODUCTINFORS";
export type PRODUCTINFORS = typeof ADDPRODUCTINFORS;

export const ADDUSERINFO = "ADDUSERINFO";
export type USERINFO = typeof ADDUSERINFO;

export const ADDPRODUCT = "ADDPRODUCT";
export type PRODUCT = typeof ADDPRODUCT;

export const REMOVEPRODUCT = "REMOVEPRODUCT";
export type SUBTRACTPRODUCT = typeof REMOVEPRODUCT;

export const MODIFYPRODUCT = "MODIFYPRODUCT";
export type UPDATEPRODUCT = typeof MODIFYPRODUCT;

export const ADDINPUTNAMEMUSTVALIDATE = "ADDINPUTNAMEMUSTVALIDATE";
export type INPUTNAMEMUSTVALIDATE = typeof ADDINPUTNAMEMUSTVALIDATE;
