export const ADDPRODUCTINFORS = "ADDPRODUCTINFORS";
export type PRODUCTINFORS = typeof ADDPRODUCTINFORS;

export const ADDUSERINFO = "ADDUSERINFO";
export type USERINFO = typeof ADDUSERINFO;

export const ADDPRODUCT = "ADDPRODUCT";
export type PRODUCT = typeof ADDPRODUCT;

export const REMOVEPRODUCT = "REMOVEPRODUCT";
export type SUBTRACTPRODUCT = typeof REMOVEPRODUCT;

export const UPDATESTATEREMOVEPRODUCT = "UPDATESTATEREMOVEPRODUCT";
export type STATEREMOVEPRODUCT = typeof UPDATESTATEREMOVEPRODUCT;

export const MODIFYPRODUCT = "MODIFYPRODUCT";
export type UPDATEPRODUCT = typeof MODIFYPRODUCT;

export const ADDINPUTNAMEMUSTVALIDATE = "ADDINPUTNAMEMUSTVALIDATE";
export type INPUTNAMEMUSTVALIDATE = typeof ADDINPUTNAMEMUSTVALIDATE;

export const MODIFYORDERID = "MODIFYORDERID";
export type UPDATEORDERID = typeof MODIFYORDERID;

export const ADDCATEGORY = "ADDCATEGORY";
export type CATEGORY = typeof ADDCATEGORY;
